variables:
  
  # Global
  prefix: "prefix"
  postfix: "101"
  location: "northeurope"

  #Tag Values
  owner: "FHIR Team"
  project     : "FHIR Patient Registry"
  environment : "dev"
  toolkit     : "Terraform"

  # Feature flags
  enable_resource_group: "true"
  # Network Feature flags
  enable_virtual_network: "true" 
  enable_subnet: "true"
  enable_subnet_peering: "true"
  # Data Feature flags
  enable_keyvault: "true"
  enable_storage_account: "true"
  enable_container_registry: "true"
  enable_log_analytics_workspace: "true"
  # Compute and Paas Feature flags
  enable_service_plan: "true"
  enable_redis_cache: "false"
  enable_application_insight: "true"
  enable_function_app: "false"
  # Healh Care feature flags
  enable_healthcare_workspace: "true"

  # Resource Custom Configuration by types:
  rg_resource: 
    - name: "FHIR100-front-end"
      tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"
    - name: "FHIR100-back-end"
      tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"

  # Network resources
  ## Virtual Network:
  vnet_resource: 
    - name: "front-end"
      resource_group_name: "FHIR100-front-end"
      address_space: ["192.168.0.0/24"]

    - name: "back-end"
      resource_group_name: "FHIR100-back-end"
      address_space: ["192.168.1.0/24"]

  ## Virtual Network Subnet:
  sub_resource: 
    - name: "sub01"
      resource_group_name: "FHIR100-front-end"
      vnet_name : "front-end"
      address_prefixes: ["192.168.0.0/25"]

    - name: "sub01"
      resource_group_name: "FHIR100-back-end"
      vnet_name : "back-end"
      address_prefixes: ["192.168.1.0/25"]

  ## Virtual Network Subnet Peering:
  subnet_peering_resource:
    - name: "peer01"
      resource_group_name: "FHIR100-front-end"
      remote_virtual_network_name: "back-end"
      virtual_network_name : "front-end"

    - name: "peer01"
      resource_group_name: "FHIR100-back-end"
      remote_virtual_network_name:  "front-end"
      virtual_network_name : "back-end"

  # Data resources
  ## Key Vault:
  akv_resource: 
      - name: "akv10"
        resource_group_name: "FHIR100-back-end"
        sku_name : "standard"
        is_sec_module : "true"
        is_private_endpoint : "true"
        vnet_name : "back-end"
        subnet_name : "sub01"
        firewall_default_action             : "Allow"

  ## Azure Container Registry:
  acr_resource:
      - name: "acr10"
        resource_group_name: "FHIR100-back-end"
        is_private_endpoint : "true"
        vnet_name : "front-end"
        subnet_name : "sub01"
        public_network_access_enabled : "true"

  ## Storage Account:
  sta_resource: 
      - name: "fhirsta100"
        resource_group_name: "FHIR100-back-end"
        vnet_name : "back-end"
        subnet_name : "sub01"
        is_sec_module : "true"


  # Compute  andd PaaS resources
  ## Application Insight:
  aai_resource: 
      - name: "aai10"
        resource_group_name: "FHIR100-front-end"

  ## App Service Plan:
  asp_resource: 
      - name: "aas10"
        resource_group_name: "FHIR100-front-end"

  ## Azure Redis Cache:
  # arc_resource: 
  #     - name: "arc10"
  #       resource_group_name: "FHIR100-front-end"

  ## Log Analytics Workspace:
  law_resource: 
      - name: "law10"
        resource_group_name: "FHIR100-back-end"

  ##Azure Health Care Workspace:
  ahcw_resource: 
      - name: "ahcw10"
        resource_group_name: "FHIR100-back-end"
        fhir_kind: "fhir-R4"

