variables:

  # Global
  prefix: "prefix"
  postfix: "101"
  location: "northeurope"

  #Tag Values
  owner: "FHIR Team"
  project     : "FHIR Patient Registry"
  environment : "dev"
  toolkit     : "Terraform"

  # Feature flags
  enable_resource_group: "true"
  enable_keyvault: "true"
  enable_storage_account: "true"
  enable_service_plan: "true"
  enable_redis_cache: "true"
  enable_application_insight: "true"
  enable_function_app: "false"
  enable_log_analytics: "false"
  enable_healthcare_workspace: "true"

  # Security Feature flags
  enable_private_endpoints: "false"

#Resource Custom Configuration:

  rg_resource: 
    - name: "FHIR01"
      tags : 
          Owner: "procha"
          Project: "FHIR Patient Registry"
          Environment: "dev"
          Toolkit: "Terraform"

    - name: "FHIR02"
      tags : 
          Owner: "Walter"
          Project: "FHIR Patient Registry"
          Environment: "dev"
          Toolkit: "Terraform"

  akv_resource:
      - name: "rett-001"
        resource_group_name: "FHIR01"
        tags:
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"
        sku_name: "standard"
        firewall_default_action: "Allow"

  sta_resource:
      - name: "rett001"
        resource_group_name: "FHIR01"
        tags:
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"

  arc_resource: 
      - name: "rett-001"
        resource_group_name: "FHIR01"
        tags:
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"

  aai_resource: 
      - name: "rett-001"
        resource_group_name: "FHIR01"
        tags:
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"

  asp_resource: 
      - name: "rett-001"
        resource_group_name: "FHIR01"
        tags: 
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"

  ahcw_resource: 
      - name: "rett001"
        resource_group_name: "FHIR01"
        tags:
           Owner: "procha"
           Project: "FHIR Patient Registry"
           Environment: "dev"
           Toolkit: "Terraform"
        fhir_kind: "fhir-Stu3"

  # Terraform remote storage
  #terraform_st_resource_group: rg-adl-terraform-state
  #terraform_st_storage_account: stadlterraformstate

  # Internals - do not touch
  #az_cli_version: 2.45.0
  #terraform_st_container_name: default