variables:

  # Global
  prefix: "prefix"
  postfix: "101"
  location: "northeurope"

  #Tag Values
  owner: "FHIR Team"
  project     : "FHIR Patient Registry"
  environment : "dev"
  toolkit     : "Terraform"

  # Feature flags
  enable_resource_group: "true"
  enable_keyvault: "true"
  enable_storage_account: "true"
  enable_service_plan: "false"
  enable_function_app: "false"
  enable_redis_cache: "true"
  enable_app_insight: "false"
  enable_log_analytics: "false"

  # Security Feature flags
  enable_private_endpoints: "false"

#Resource Custom Configuration:

  rg_resource: 
    - name: "FHIR01"
      tags : 
          Owner: "Pedro"
          Project     : "FHIR Patient Registry"
          Environment : "dev"
          Toolkit     : "Terraform"
        
      
    - name: "FHIR02"
      tags : 
          Owner: "Walter"
          Project     : "FHIR Patient Registry"
          Environmentt : "dev"
          Toolkit     : "Terraform"

  akv_resource: 
      - name: "akv10"
        resource_group_name: "FHIR01"
        tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"
        sku_name : "standard"
        firewall_default_action             : "Allow"

  sta_resource: 
      - name: "fhirsta10"
        resource_group_name: "FHIR01"
        tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"

  arc_resource: 
      - name: "arc10"
        resource_group_name: "FHIR01"
        tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"

  aai_resource: 
      - name: "aai10"
        resource_group_name: "FHIR01"
        tags : 
           Owner: "Walter"
           Project     : "FHIR Patient Registry"
           Environmentt : "dev"
           Toolkit     : "Terraform"
    

  # Terraform remote storage
  #terraform_st_resource_group: rg-adl-terraform-state
  #terraform_st_storage_account: stadlterraformstate

  # Internals - do not touch
  #az_cli_version: 2.45.0
  #terraform_st_container_name: default