name: Deploy infra

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
  push:
    branches:
      [main]
    paths:
      - '.github/workflows/terraform.yml'
      - 'modules/**'

permissions:
  id-token: write
  contents: read

jobs:     
  Init-terraform:
    name: Init Terraform for Azure resources
    runs-on: ubuntu-latest
    environment: Azure

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan

  Apply-terraform:
    runs-on: ubuntu-latest
    needs: Init-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v2
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply tfplan