name: Terraform Plan and Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: Azure

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Save Plan Artifacts
        if: steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Apply
        run: |
          pwd
          ls -R
          terraform apply tfplan/terraform-plan
        env:
          TF_INPUT: false
          TF_IN_AUTOMATION: true
          TF_VAR_approval_required: "true" # set a variable to require approval

      - name: Cleanup Plan Artifacts
        run: rm tfplan

  terraform-approval:
    name: Terraform Approval
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Show Plan
        run: terraform show tfplan

      - name: Request Approval
        uses: unsplash/request-approval@v1
        with:
          message: |
            **Terra