name: Terraform Plan and Apply for Develop and Feature Branches
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - feature/*
  #  paths:
  #     - '.github/workflows/*'
  #     - 'modules/**'
  #     - 'modules/**'

env:
  # terraform_workingdir: ""
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: Visual_Studio_Subscription

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false

      - name: Install terraform-plan-summary
        run: |
          REPO="dineshba/terraform-plan-summary"
          curl -LO https://github.com/$REPO/releases/latest/download/tf-summarize_linux_amd64.zip
          tmpDir=$(mktemp -d -t tmp.XXXXXXXXXX)
          mv tf-summarize_linux_amd64.zip $tmpDir
          cd $tmpDir
          unzip tf-summarize_linux_amd64.zip
          chmod +x tf-summarize
          echo $PWD >> $GITHUB_PATH

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Summary of changes
        run: terraform show -json tfplan | tf-summarize

      - name: Save Plan Artifacts
        if: steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - uses: liatrio/terraform-change-pr-commenter@v1.4.0
        with:
          json-file: my-tfplan.json
          expand-comment: "true"

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: Visual_Studio_Subscription

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply tfplan/tfplan
        env:
          TF_INPUT: false
          TF_IN_AUTOMATION: true
          TF_VAR_approval_required: "true"

      - name: Cleanup Plan Artifacts
        run: rm tfplan/tfplan
